### Basic test: all blas present

In [2]:
import json
import lib.c_fct as c_fct
j = None

with open('data/blases.json') as f:
    j = json.load(f)
    f.close()

c_fcts = c_fct.fcts_in("data/blas.h")

impl = set(j["hash"].keys())
todo = set([fct.name for fct in c_fcts])

print(f'Number of functions implemented: {len(impl)}')
print(f'Implemented but not in todo: {impl-todo}')
print(f'Todo but not implemented:    {todo-impl}')

Number of functions implemented: 164
Implemented but not in todo: set()
Todo but not implemented:    set()


### Reading arguments

In [1]:
import json
import lib.c_fct as c_fct
j = None

with open('data/blases.json') as f:
    j = json.load(f)
    f.close()

    
c_fcts = c_fct.fcts_in("data/blas.h")

sdsdot	['n', 'alpha', 'x', 'incx', 'y', 'incy']
dsdot	['n', 'x', 'incx', 'y', 'incy']
sdot	['n', 'x', 'incx', 'y', 'incy']
ddot	['n', 'x', 'incx', 'y', 'incy']
cdotu	['n', 'x', 'incx', 'y', 'incy']
cdotc	['n', 'x', 'incx', 'y', 'incy']
zdotu	['n', 'x', 'incx', 'y', 'incy']
zdotc	['n', 'x', 'incx', 'y', 'incy']
isamax	['n', 'x', 'incx']
idamax	['n', 'x', 'incx']
icamax	['n', 'x', 'incx']
izamax	['n', 'x', 'incx']
isamin	['n', 'x', 'incx']
idamin	['n', 'x', 'incx']
icamin	['n', 'x', 'incx']
izamin	['n', 'x', 'incx']
ismax	['n', 'x', 'incx']
idmax	['n', 'x', 'incx']
icmax	['n', 'x', 'incx']
izmax	['n', 'x', 'incx']
ismin	['n', 'x', 'incx']
idmin	['n', 'x', 'incx']
icmin	['n', 'x', 'incx']
izmin	['n', 'x', 'incx']
sasum	['n', 'x', 'incx']
dasum	['n', 'x', 'incx']
scasum	['n', 'x', 'incx']
dzasum	['n', 'x', 'incx']
ssum	['n', 'x', 'incx']
dsum	['n', 'x', 'incx']
scsum	['n', 'x', 'incx']
dzsum	['n', 'x', 'incx']
saxpy	['n', 'alpha', 'x', 'incx', 'y', 'incy']
daxpy	['n', 'alpha', 'x', 'incx',

### Generating tests

In [14]:
import json
import lib.c_fct as c_fct
import copy
import scipy.linalg.blas as blas

j = None

with open('data/vars.json') as f_vars:
    vars = json.load(f_vars)

def build_vars(names):
    return copy.deepcopy([vars[name] if isinstance(name, str) else name for name in names])


with open('data/test_cases.json') as f_test:
    tests = json.load(f_test)
    for fct in tests.keys():
        print(f'{fct} {build_vars(tests[fct])}')

print(blas.caxpy([1,2],[3,4]))


saxpy [10, 2, [1, 3, -2, 4, 3, 1, 5, 23, -2, 6], 1, [5, 8, 2, -9, 2, 123, -5, 23, 6, 5], 1]
daxpy [10, 2, [1, 3, -2, 4, 3, 1, 5, 23, -2, 6], 1, [5, 8, 2, -9, 2, 123, -5, 23, 6, 5], 1]
caxpy [5, 2, [1, 3, -2, 4, 3, 1, 5, 23, -2, 6], 1, [5, 8, 2, -9, 2, 123, -5, 23, 6, 5], 1]
zaxpy [5, 2, [1, 3, -2, 4, 3, 1, 5, 23, -2, 6], 1, [5, 8, 2, -9, 2, 123, -5, 23, 6, 5], 1]
[4.+0.j 6.+0.j]


In [5]:
import json
import lib.c_fct as c_fct
import copy
import scipy.linalg.blas as blas

x= [1,-2,3,-4]
y= [3,2,0,-2]

print(blas.caxpy(x,y,a=[1,0]))




[ 4.+0.j  0.+0.j  3.+0.j -6.+0.j]


In [7]:
import json
import lib.c_fct as c_fct
import copy
import scipy.linalg.blas as blas

x= [1+(-2j),3+(-4j)]
y= [3+2j,-2j]

print(blas.caxpy(x,y,a=1))

[4.+0.j 3.-6.j]


In [3]:
import numpy as np

# Define the complex matrix 'a' and the complex vector 'x'
a = np.array([[1+0j, 3], [0, 7j]])
x = np.array([-1+2j, -3+4j])

# Compute the matrix multiplication 'a*x'
result = np.matmul(a, x[:, np.newaxis])

# Print the result
print(result.flatten())

[-10.+14.j -28.-21.j]


In [18]:
import numpy as np

A = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]).reshape(3,3)
B = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0]).reshape(3,4)
C = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0]).reshape(3,4)


import scipy.linalg.blas as blas

print(blas.ssymm(2, A,B, beta=3, c=C).flatten())

[ 79.  94. 109. 124. 177. 206. 235. 264. 255. 294. 333. 372.]


In [28]:
import numpy as np

#A = np.array([[0,1,2],[5,6,7],[10,11,12],[15,16,0]])
A = np.array([[0,5,10,15], [1,6,11,16], [2,7,12,0]])
X = np.array([1.0, 2.0, 3.0, 4.0])
Y = np.array([5.0, 6.0, 7.0, 8.0])


import scipy.linalg.blas as blas

print(blas.sgbmv(4, 4, 1, 1, 1.0, A,X, beta=0.5, y=Y).flatten())

[ 13.5  47.  110.5 104. ]


In [29]:
import numpy as np
#sgbmv
A = np.array([1,2,0,0, 5,6,7,0, 0,10,11,12, 0,0,15,16]).reshape(4,4)
X = np.array([1,2,3,4])

print(np.matmul(A,X))

[  5  38 101 109]


In [35]:
import numpy as np
#sgbmv
#1.0, 2.0, 3.0,    4.0, 5.0, 6.0,    7.0, 8.0, 9.0,    10.0, 11.0, 12.0,    13.0, 14.0, 15.0
A = np.array([
    1, 2, 3, 0, 0,
    2, 4, 5, 6, 0,
    3, 5, 7, 8, 9,
    0, 6, 8,10,11,
    0, 0, 9,11,13]).reshape(5,5)
X = np.array([1,2,3,4, 5])

print(np.matmul(A,X))

[ 14  49 111 131 136]


In [39]:
A = np.array([1.0, 2.0, 3.0, 2.0, 4.0, 5.0, 3.0, 5.0, 6.0]).reshape(3,3)
X = np.array([1,2,3])

print((2*np.matmul(X,X.T) + A).flatten())

[29. 30. 31. 30. 32. 33. 31. 33. 34.]


In [42]:
# ssyrk
A = np.array([1.0, 2.0, 3.0, 2.0, 4.0, 5.0, 3.0, 5.0, 6.0]).reshape(3,3)

print((np.matmul(A.T,A)))

[[14. 25. 31.]
 [25. 45. 56.]
 [31. 56. 70.]]


In [43]:
A = np.array([1.0, 2.0, 3.0, 2.0, 4.0, 5.0, 3.0, 5.0, 6.0]).reshape(3,3)
X = np.array([1,2,3])
Y = np.array([4,5,6])

print((2*np.matmul(X,Y.T) + 2*(np.matmul(Y, X.T))+ A).flatten())

[129. 130. 131. 130. 132. 133. 131. 133. 134.]


In [16]:
import numpy as np
#ctrmm
A = np.array([1,2, 3,4, 0,0, 5,6], dtype='f').reshape(2,4).view(np.complex64)
B = np.array([1,2, 3,4, 0,0, 1,1], dtype='f').reshape(2,4).view(np.complex64)

def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float32))
    print(S.replace('.',','))

pretty_print(((1+2j)*np.matmul(A,B)))

[-11,  -2, -40,   5,   0,   0, -23,   9,]


In [54]:
import numpy as np
#ctpsv

A = np.array([1,1, 2,2, 0,0, 3,3], dtype='f').reshape(2,4).view(np.complex64)
X = np.array([1,2, 3,4], dtype='f').view(np.complex64)


def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float32))
    print(S.replace('.',','))

pretty_print((np.matmul(A,X)))

[-3, 17, -3, 21,]


In [26]:
import numpy as np
#ctpmv

A = np.array([1,2, 3,4, 0,0, 5,6], dtype='f').reshape(2,4).view(np.complex64)
X = np.array([1,2, 3,4], dtype='f').view(np.complex64)

def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float32))
    print(S.replace('.',','))

pretty_print((np.matmul(A,X)))

[-10,  28,  -9,  38,]


In [64]:
import numpy as np
#ctbsv

A = np.array([1,0, 2,2, 0,0, 1,0], dtype='f').reshape(2,4).view(np.complex64)
X = np.array([1.0,0.0,1.0,0.0], dtype='f').reshape(1,4).view(np.complex64).T

print(X)

def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float32))
    print(S.replace('.',','))

pretty_print((np.matmul(A,X)))

[[1.+0.j]
 [1.+0.j]]
[3, 2, 1, 0,]


In [29]:
import numpy as np
#ctbsv

A = np.array([1,1, 2,2, 0,0, 3,3], dtype='f').reshape(2,4).view(np.complex64)
C = np.array([0,0, 0,0, 0,0, 0,0], dtype='f').reshape(2,4).view(np.complex64)

def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float32))
    print(S.replace('.',','))

pretty_print(((1+2j)*np.matmul(A,A.T)) + (1j*C))

[-20,  10, -24,  12, -24,  12, -36,  18,]


In [67]:
import numpy as np
#csyrk

A = np.array([1,2, 3,4, 5,6, 7,8], dtype='f').reshape(2,4).view(np.complex64)
C = np.array([0,0, 0,0, 0,0, 0,0], dtype='f').reshape(2,4).view(np.complex64)

def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float32))
    print(S.replace('.','.0,'))

pretty_print((1+2j)*(np.matmul(A,A.T) + (1j*C)))

[ -66.0,    8.0, -154.0,   32.0, -154.0,   32.0, -370.0,  120.0,]


In [68]:
import numpy as np
#csyrk2

A = np.array([1,1, 2,2, 0,0, 3,3], dtype='f').reshape(2,4).view(np.complex64)
B = np.array([0,1, 2,0, 0,0, 0,0], dtype='f').reshape(2,4).view(np.complex64)
C = np.array([0,0, 0,0, 0,0, 1,0], dtype='f').reshape(2,4).view(np.complex64)

def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float32))
    print(S.replace('.',','))

pretty_print(((1.5+1j)*(np.matmul(A,B.T) + np.matmul(B, A.T))) + (0.5*C))

[-1,  21,   3,  15,   3,  15,   0,5  0, ]


In [ ]:
import numpy as np
#csymm

A = np.array([1,1, 2,2, 0,0, 3,3], dtype='f').reshape(2,4).view(np.complex64)
B = np.array([0,1, 2,0, 0,0, 0,0], dtype='f').reshape(2,4).view(np.complex64)
C = np.array([0,0, 0,0, 0,0, 1,0], dtype='f').reshape(2,4).view(np.complex64)

def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float32))
    print(S.replace('.',','))

pretty_print(((1.5+1j)*(np.matmul(A,B.T) + np.matmul(B, A.T))) + (1j*C))

In [48]:
#ssyr
A = np.array([
    1.0, 2.0, 3.0,
    0.0, 4.0, 5.0,
    0.0, 0.0, 6.0]).reshape(3,3)
X = np.array([1,2,3]).reshape(3,1)

def pretty_print(Arr):
    S = str(Arr.flatten())
    print(S.replace('.','.0,'))

print(np.matmul(X,X.T))
pretty_print((2*np.matmul(X,X.T) + A).flatten())

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[ 3.0,  6.0,  9.0,  4.0, 12.0, 17.0,  6.0, 12.0, 24.0,]


In [52]:
#ssyr2k
A = np.array([1.0, 2.0, 3.0, 3.0, 5.0, 6.0, 2.0, 1.0, 9.0]).reshape(3,3)
B = np.array([1.0, 2.0, 3.0, 2.0, 1.0, 2.0, 3.0, 2.0, 1.0]).reshape(3,3)
C = np.array([1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]).reshape(3,3)

def pretty_print(Arr):
    S = str(Arr.flatten())
    print(S.replace('.','.0,'))

pretty_print((np.matmul(A,B.T) + np.matmul(B,A.T) + (1*C)))

[29.0, 41.0, 41.0, 41.0, 47.0, 48.0, 41.0, 48.0, 35.0,]


In [53]:
#ssyr2
A = np.array([
    1.0, 2.0, 3.0,
    0.0, 4.0, 5.0,
    0.0, 0.0, 6.0]).reshape(3,3)
X = np.array([1,2,3]).reshape(3,1)
Y = np.array([4,5,6]).reshape(3,1)

def pretty_print(Arr):
    S = str(Arr.flatten())
    print(S.replace('.','.0,'))

pretty_print((2*np.matmul(X,Y.T) + 2*np.matmul(Y, X.T) + A).flatten())

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[17.0, 28.0, 39.0, 26.0, 44.0, 59.0, 36.0, 54.0, 78.0,]


In [70]:
#cher
A = np.array([2,0, 1,-2, 1,2, 4,5], dtype='f').reshape(2,4).view(np.complex64)
X = np.array([1.0,2.0,3.0,4.0], dtype='f').reshape(1,4).view(np.complex64).T

print(X)

def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float32))
    print(S.replace('.','.0,'))

pretty_print(((2+3j)*np.matmul(X,X.T)) + A)

[[1.+2.j]
 [3.+4.j]]
[-16.0,  -1.0, -39.0,   3.0, -39.0,   7.0, -82.0,  32.0,]


In [86]:
#cherk2

A = np.matrix(np.array([1.0, 2.0, 3.0, 3.0, 5.0, 6.0, 2.0, 1.0], dtype='f').reshape(2,4).view(np.complex64))
B = np.matrix(np.array([1.0, 0.0, 3.0, 5.0, 4.0, 1.0, 2.0, 0.0], dtype='f').reshape(2,4).view(np.complex64))
C = np.matrix(np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], dtype='f').reshape(2,4).view(np.complex64))

def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float64))
    print(S.replace('. ', '.0, '))


pretty_print((1+2j)*np.matmul(A,B.getH()) + (1-2j)*np.matmul(B,A.getH()) )

[[ 66.0,   0.0,   4.0,   6.0,   4.0,  -6.0, -24.0,   0.]]


In [91]:
# cher2

A = np.array([2,0, 1,-2, 1,2, 4,5], dtype='f').reshape(2,4).view(np.complex64)
X = np.matrix(np.array([1.0,2.0,3.0,4.0], dtype='f').reshape(1,4).view(np.complex64)).T
Y = np.matrix(np.array([5.0,6.0,7.0,8.0], dtype='f').reshape(1,4).view(np.complex64)).T


def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float64))
    print(S.replace('.', '.0,'))

pretty_print((2*np.matmul(X,Y.getH()) + 2*np.matmul(Y,X.getH())) + A)

[[ 70.0,   0.0, 125.0,   6.0, 125.0,  -6.0, 216.0,   5.0,]]


In [92]:
# chemv

A = np.array([2,0, 1,-2, 1,2, 4,5], dtype='f').reshape(2,4).view(np.complex64)
X = np.matrix(np.array([1.0,2.0,3.0,4.0], dtype='f').reshape(1,4).view(np.complex64)).T
Y = np.matrix(np.array([5.0,6.0,7.0,8.0], dtype='f').reshape(1,4).view(np.complex64)).T


def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float64))
    print(S.replace('.', '.0,'))

pretty_print((np.matmul(A,X) + 2j*Y))

[[  1.0,  12.0, -27.0,  49.0,]]


In [99]:
#chemm

A = np.matrix(np.array([1.0, 0.0, 3.0, 4.0, 3.0, -4.0, 2.0, 0.0], dtype='f').reshape(2,4).view(np.complex64))
B = np.matrix(np.array([1.0, 0.0, 3.0, 5.0, 4.0, 1.0, 2.0, 0.0], dtype='f').reshape(2,4).view(np.complex64))


print(A)

def pretty_print(Arr):
    S = str(Arr.flatten().view(np.float32))
    print(S.replace('. ', '.0, '))


pretty_print(np.matmul(A,B))

[[1.+2.j 3.+4.j]
 [3.-4.j 2.+1.j]]
[[ 9.0, 21.0, -1.0, 19.0, 10.0,  2.0, 33.0,  5.]]
